pipeline{
    agent any
    tools{
        maven 'null'
    }
    stages{
      stage("maven1"){
        steps{
        sh 'mvn clean validate compile install test package'
        }
      }  
    }
}