pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage('clean'){
            steps{
                sh 'mvn clean'
            }
        }
        stage('install'){
            steps{
                sh 'mvn install'
            }
        }
        stage('package'){
            steps{
                sh 'mvn package'
            }
        }
        stage('artfactory'){
            steps{
                sh 'curl -uAdmin:APBLMvC9LuW1SZwNeJouaRZ2xBh -T target/bio*.jar "http://100.26.228.10:8081/artifactory/geolocation/ybamal"'
            }
        }
    
       
    }
}

