pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
      stage("maven1"){
        steps{
        sh 'mvn clean validate compile install test package'
        }
      }  
      stage('upload artifact'){
        steps{
            sh 'curl -uAdmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \ 
            target/bio*.jar \
             "http://ec2-100-25-144-234.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
        }
      }
    }
}